name: Release CI
on:
  push:
    branches:
      - release
jobs:
  deploy:
    # A strategy is used to define various build environments this job will run.
    #
    # To say it simple, this will create 3 separate independent jobs which will
    # run on ubuntu, mac & windows.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    # Runs when the commit message contains "[Released]"
    # if: "contains(github.event.head_commit.message, '[Released]')"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        run: cargo build --release

      - name: Package for Debian
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo deb
          strip target/release/test_gh_actions
          mkdir -p release
          mv target/debian/*.deb ./release/test_gh_actions-linux.deb
          tar -C ./target/release/ -czvf ./release/test_gh_actions-linux.tar.gz ./test_gh_actions
      
      - name: Package pure binary
        if: matrix.os == 'ubuntu-latest'
        run: |
          strip target/release/test_gh_actions
          mkdir -p release
          mv target/release/test_gh_actions ./release/test_gh_actions

      - name: Get changelog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 2
          path: ./CHANGELOG.md
      # This will draft a new release & will attach the binaries produced by the above outputs.
      # You still need to publish this release though after job ends.
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.changelog_reader.outputs.version }}
          release_name: Release ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: true
          files: |
            ./release/*.tar.gz
            ./release/*.deb
            ./release/test_gh_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
